[package]
name = "l094-16-combine-earlier-category-averages-with-shared-level-threshold-trees"
version = "0.1.0"
edition = "2024"

[dependencies]
l091_16_predict_tree_output_by_choosing_leaf_with_shared_threshold_tests = { package = "l091-16-predict-tree-output-by-choosing-leaf-with-shared-threshold-tests", path = "../l091-16-predict-tree-output-by-choosing-leaf-with-shared-threshold-tests" }
l092_16_encode_categories_as_average_previous_targets_with_prior_weight = { package = "l092-16-encode-categories-as-average-previous-targets-with-prior-weight", path = "../l092-16-encode-categories-as-average-previous-targets-with-prior-weight" }
