[package]
name = "l196-36-reduce-context-computation-by-sharing-keys-and-values-across-query-groups"
version = "0.1.0"
edition = "2024"

[dependencies]
l186_35_calc_softmax_probability_weights_by_exponentiating_shifted_scores_then_dividing_by_sum_where_weights_sum_to_1_and_larger_scores_get_larger_shares = { package = "l186-35-calc-softmax-probability-weights-by-exponentiating-shifted-scores-then-dividing-by-sum-where-weights-sum-to-1-and-larger-scores-get-larger-shares", path = "../l186-35-calc-softmax-probability-weights-by-exponentiating-shifted-scores-then-dividing-by-sum-where-weights-sum-to-1-and-larger-scores-get-larger-shares" }
