[package]
name = "l010-02-multiply-matrix-and-vector-by-adding-multiplied-row-coordinates"
version = "0.1.0"
edition = "2024"

[dependencies]
l001_01_multiply_matching_coordinates_then_add_results = { package = "l001-01-multiply-matching-coordinates-then-add-results", path = "../l001-01-multiply-matching-coordinates-then-add-results" }

lesson-visualization = { path = "../lesson-visualization" }
