[package]
name = "part-186-lesson-35-convert-text-identifiers-to-context-and-next-piece-scores"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
part-182-lesson-35-calculate-past-context-by-summing-current-and-past-values-with-match-weights = { path = "../part-182-lesson-35-calculate-past-context-by-summing-current-and-past-values-with-match-weights" }
