[package]
name = "part-054-lesson-09-linear-regression"
version = "0.1.0"
edition = "2024"

[dependencies]
part_049_lesson_09_mean_squared_error = { package = "part-049-lesson-09-mean-squared-error", path = "../part-049-lesson-09-mean-squared-error" }

lesson-visualization = { path = "../lesson-visualization" }
