[package]
name = "part-235-lesson-46-end-to-end"
version = "0.1.0"
edition = "2024"

[dependencies]
part_029_lesson_06_mean = { package = "part-029-lesson-06-mean", path = "../part-029-lesson-06-mean" }
part_050_lesson_09_mean_absolute_error = { package = "part-050-lesson-09-mean-absolute-error", path = "../part-050-lesson-09-mean-absolute-error" }

lesson-visualization = { path = "../lesson-visualization" }
