[package]
name = "part-139-lesson-26-increase-gaps-between-past-signal-values-used-by-filter"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
part-138-lesson-26-sum-weighted-current-and-past-signal-values = { path = "../part-138-lesson-26-sum-weighted-current-and-past-signal-values" }
lesson-visualization = { path = "../lesson-visualization" }
