[package]
name = "l070-11-practice-checking-predictions-when-one-class-is-rare"
version = "0.1.0"
edition = "2024"

[dependencies]
l061_11_count_correct_and_incorrect_positive_and_negative_predictions = { package = "l061-11-count-correct-and-incorrect-positive-and-negative-predictions", path = "../061-11-count-correct-and-incorrect-positive-and-negative-predictions" }
l062_11_count_classification_outcomes_by_comparing_scores_with_threshold = { package = "l062-11-count-classification-outcomes-by-comparing-scores-with-threshold", path = "../062-11-count-classification-outcomes-by-comparing-scores-with-threshold" }
l063_11_calculate_accuracy_as_correct_predictions_divided_by_all_predictions = { package = "l063-11-calculate-accuracy-as-correct-predictions-divided-by-all-predictions", path = "../063-11-calculate-accuracy-as-correct-predictions-divided-by-all-predictions" }
l064_11_calculate_positive_prediction_precision_as_true_positives_over_positive_predictions = { package = "l064-11-calculate-positive-prediction-precision-as-true-positives-over-positive-predictions", path = "../064-11-calculate-positive-prediction-precision-as-true-positives-over-positive-predictions" }
l065_11_calculate_positive_detection_recall_as_found_positives_over_actual_positives = { package = "l065-11-calculate-positive-detection-recall-as-found-positives-over-actual-positives", path = "../065-11-calculate-positive-detection-recall-as-found-positives-over-actual-positives" }
l066_11_calculate_f1_score_as_twice_precision_times_recall_over_their_sum = { package = "l066-11-calculate-f1-score-as-twice-precision-times-recall-over-their-sum", path = "../066-11-calculate-f1-score-as-twice-precision-times-recall-over-their-sum" }
lesson-trace = { path = "../lesson-trace" }

lesson-visualization = { path = "../lesson-visualization" }
