[package]
name = "l050-09-calc-mean-squared-error-by-summing-squared-errors-and-dividing-by-count-where-0-means-exact-predictions-and-larger-means-worse"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-float-comparison = { path = "../lesson-float-comparison" }

lesson-visualization = { path = "../lesson-visualization" }
