[package]
name = "l170-31-calc-scaled-match-score-by-multiplying-query-and-key-then-dividing-sum"
version = "0.1.0"
edition = "2024"

[dependencies]
l001_01_multiply_matching_coords_then_add_results_where_pos_means_angle_below_90_neg_means_angle_above_90_and_0_means_perpendicular_or_zero_vec = { package = "l001-01-multiply-matching-coords-then-add-results-where-pos-means-angle-below-90-neg-means-angle-above-90-and-0-means-perpendicular-or-zero-vec", path = "../l001-01-multiply-matching-coords-then-add-results-where-pos-means-angle-below-90-neg-means-angle-above-90-and-0-means-perpendicular-or-zero-vec" }

lesson-visualization = { path = "../lesson-visualization" }
