[package]
name = "l170-31-calc-scaled-match-score-by-multiplying-query-and-key-then-dividing-sum"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-float-comparison = { path = "../lesson-float-comparison" }
l001_01_multiply_matching_coords_then_add_results = { package = "l001-01-multiply-matching-coords-then-add-results", path = "../l001-01-multiply-matching-coords-then-add-results" }
