[package]
name = "l055-09-practice-fitting-a-line-and-checking-prediction-errors"
version = "0.1.0"
edition = "2024"

[dependencies]
l050_09_calc_mean_squared_error_by_summing_squared_errors_and_dividing_by_count_where_0_means_exact_predictions_and_larger_means_worse = { package = "l050-09-calc-mean-squared-error-by-summing-squared-errors-and-dividing-by-count-where-0-means-exact-predictions-and-larger-means-worse", path = "../l050-09-calc-mean-squared-error-by-summing-squared-errors-and-dividing-by-count-where-0-means-exact-predictions-and-larger-means-worse" }

lesson-visualization = { path = "../lesson-visualization" }
