[package]
name = "l055-09-practice-fitting-a-line-and-checking-prediction-errors"
version = "0.1.0"
edition = "2024"

[dependencies]
l050_09_calc_mean_squared_error_by_summing_squared_errors_and_dividing_by_count = { package = "l050-09-calc-mean-squared-error-by-summing-squared-errors-and-dividing-by-count", path = "../l050-09-calc-mean-squared-error-by-summing-squared-errors-and-dividing-by-count" }
