[package]
name = "part-235-lesson-46-end-to-end-ml-project-from-baseline-to-inference"
version = "0.1.0"
edition = "2024"

[dependencies]
part_029_lesson_06_arithmetic_mean_of_numeric_values = { package = "part-029-lesson-06-arithmetic-mean-of-numeric-values", path = "../part-029-lesson-06-arithmetic-mean-of-numeric-values" }
part_050_lesson_09_mean_absolute_error_between_targets_and_predictions = { package = "part-050-lesson-09-mean-absolute-error-between-targets-and-predictions", path = "../part-050-lesson-09-mean-absolute-error-between-targets-and-predictions" }

lesson-visualization = { path = "../lesson-visualization" }
