[package]
name = "l197-36-scale-query-and-key-vecs-by-their-root-mean-square"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-float-comparison.workspace = true
l194_36_normalize_vec_scale_by_dividing_coords_by_root_mean_square_then_applying_weights.workspace = true
l195_36_rotate_vec_coord_pair_by_token_position.workspace = true
