[package]
name = "l007-01-practice-multiplying-coords-vec-lens-and-point-dists"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-float-comparison.workspace = true
l001_01_multiply_matching_coords_then_add_results.workspace = true
l002_01_calc_sum_of_absolute_vec_coords.workspace = true
l003_01_calc_vec_len_as_square_root_of_sum_of_squared_coords.workspace = true
l005_01_calc_point_dist_as_square_root_of_sum_of_squared_coord_diffs.workspace = true
l006_01_multiply_matching_coords_then_add_results_and_normalize_by_both_vec_lens.workspace = true
