[package]
name = "part-187-lesson-35-train-output-weights-while-keeping-context-model-fixed"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
part-186-lesson-35-convert-text-identifiers-to-context-and-next-piece-scores = { path = "../part-186-lesson-35-convert-text-identifiers-to-context-and-next-piece-scores" }
