[package]
name = "part-215-lesson-42-compare-feature-means-to-detect-changed-data"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
part_029_lesson_06_calculate_mean_by_summing_values_and_dividing_by_count = { package = "part-029-lesson-06-calculate-mean-by-summing-values-and-dividing-by-count", path = "../part-029-lesson-06-calculate-mean-by-summing-values-and-dividing-by-count" }

lesson-visualization = { path = "../lesson-visualization" }
