[package]
name = "l062-11-calculate-positive-detection-recall-as-found-positives-over-actual-positives"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
l060_11_count_correct_and_incorrect_positive_and_negative_predictions = { package = "l060-11-count-correct-and-incorrect-positive-and-negative-predictions", path = "../060-11-count-correct-and-incorrect-positive-and-negative-predictions" }

lesson-visualization = { path = "../lesson-visualization" }
