[package]
name = "part-176-lesson-33-mix-information-between-all-image-blocks-using-weights"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
part-175-lesson-33-create-image-block-sequence-by-splitting-image-into-nonoverlapping-squares = { path = "../part-175-lesson-33-create-image-block-sequence-by-splitting-image-into-nonoverlapping-squares" }
lesson-visualization = { path = "../lesson-visualization" }
