[package]
name = "part-176-lesson-33-mix-information-between-all-image-blocks-using-weights"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
part-175-lesson-33-split-square-image-into-nonoverlapping-square-blocks = { path = "../part-175-lesson-33-split-square-image-into-nonoverlapping-square-blocks" }
lesson-visualization = { path = "../lesson-visualization" }
