[package]
name = "l054-09-practice-fitting-a-line-and-checking-prediction-errors"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
l049_09_calculate_mean_squared_error_as_squared_error_sum_divided_by_count = { package = "l049-09-calculate-mean-squared-error-as-squared-error-sum-divided-by-count", path = "../049-09-calculate-mean-squared-error-as-squared-error-sum-divided-by-count" }

lesson-visualization = { path = "../lesson-visualization" }
