[package]
name = "l191-35-calculate-text-context-vectors-by-adding-position-and-weighted-past-context"
version = "0.1.0"
edition = "2024"

[dependencies]
l187_35_calculate_past_context_by_summing_current_and_past_values_with_match_weights = { package = "l187-35-calculate-past-context-by-summing-current-and-past-values-with-match-weights", path = "../187-35-calculate-past-context-by-summing-current-and-past-values-with-match-weights" }
lesson-trace = { path = "../lesson-trace" }
