[package]
name = "part-063-lesson-11-harmonic-mean-of-precision-and-recall"
version = "0.1.0"
edition = "2024"

[dependencies]
part_060_lesson_11_confusion_matrix = { package = "part-060-lesson-11-confusion-matrix", path = "../part-060-lesson-11-confusion-matrix" }
part_061_lesson_11_precision = { package = "part-061-lesson-11-precision", path = "../part-061-lesson-11-precision" }
part_062_lesson_11_recall = { package = "part-062-lesson-11-recall", path = "../part-062-lesson-11-recall" }

lesson-visualization = { path = "../lesson-visualization" }
