[package]
name = "l208-40-compare-fixed-and-input-controlled-memory-retention"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
l206-40-calculate-memory-states-by-adding-weighted-input-to-retained-previous-state = { path = "../206-40-calculate-memory-states-by-adding-weighted-input-to-retained-previous-state" }
lesson-visualization = { path = "../lesson-visualization" }
