[package]
name = "l067-11-calc-f1-score-from-counts-by-multiplying-precision-and-recall-by-two-then-dividing-by-sum"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-float-comparison.workspace = true
l061_11_count_binary_classification_outcomes_from_targets_and_predictions.workspace = true
l064_11_calc_pos_prediction_precision_as_true_poss_divided_by_pos_predictions.workspace = true
l065_11_calc_pos_detection_recall_as_true_poss_divided_by_actual_poss.workspace = true
l066_11_calc_f1_score_as_twice_precision_times_recall_divided_by_their_sum.workspace = true
