[package]
name = "l184-34-predict-hidden-text-piece-from-surrounding-context"
version = "0.1.0"
edition = "2024"

[dependencies]
l182_34_calc_visible_context_by_summing_states_weighted_by_exponentiated_coord_scores = { package = "l182-34-calc-visible-context-by-summing-states-weighted-by-exponentiated-coord-scores", path = "../l182-34-calc-visible-context-by-summing-states-weighted-by-exponentiated-coord-scores" }
