[package]
name = "l063-11-calculate-accuracy-as-correct-predictions-divided-by-all-predictions"
version = "0.1.0"
edition = "2024"

[dependencies]
l061_11_count_correct_and_incorrect_positive_and_negative_predictions = { package = "l061-11-count-correct-and-incorrect-positive-and-negative-predictions", path = "../l061-11-count-correct-and-incorrect-positive-and-negative-predictions" }
lesson-trace = { path = "../lesson-trace" }
