[package]
name = "part-003-lesson-01-calculate-vector-length-as-square-root-of-sum-of-squared-coordinates"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
part_001_lesson_01_calculate_scalar_product_by_multiplying_matching_coordinates_and_adding = { package = "part-001-lesson-01-calculate-scalar-product-by-multiplying-matching-coordinates-and-adding", path = "../part-001-lesson-01-calculate-scalar-product-by-multiplying-matching-coordinates-and-adding" }

lesson-visualization = { path = "../lesson-visualization" }
