[package]
name = "l071-12-calculate-squared-example-distance-by-summing-squared-feature-differences"
version = "0.1.0"
edition = "2024"

[dependencies]
l004_01_calculate_squared_point_distance_by_summing_squared_coordinate_differences = { package = "l004-01-calculate-squared-point-distance-by-summing-squared-coordinate-differences", path = "../004-01-calculate-squared-point-distance-by-summing-squared-coordinate-differences" }
lesson-trace = { path = "../lesson-trace" }

lesson-visualization = { path = "../lesson-visualization" }
