[package]
name = "l149-27-encode-and-decode-text-using-learned-pair-merges"
version = "0.1.0"
edition = "2024"

[dependencies]
l148_27_train_text_tokenizer_by_repeatedly_merging_most_frequent_adjacent_pair = { package = "l148-27-train-text-tokenizer-by-repeatedly-merging-most-frequent-adjacent-pair", path = "../l148-27-train-text-tokenizer-by-repeatedly-merging-most-frequent-adjacent-pair" }
