[package]
name = "l151-27-compare-byte-splitting-and-learned-text-pieces-on-new-strings"
version = "0.1.0"
edition = "2024"

[dependencies]
l148_27_learn_text_units_by_merging_most_frequent_adjacent_byte_pairs = { package = "l148-27-learn-text-units-by-merging-most-frequent-adjacent-byte-pairs", path = "../l148-27-learn-text-units-by-merging-most-frequent-adjacent-byte-pairs" }
lesson-trace = { path = "../lesson-trace" }
lesson-visualization = { path = "../lesson-visualization" }
