[package]
name = "l241-46-project-compare-train-and-run-prediction-model"
version = "0.1.0"
edition = "2024"

[dependencies]
l030_06_calculate_mean_by_summing_values_and_dividing_by_count = { package = "l030-06-calculate-mean-by-summing-values-and-dividing-by-count", path = "../l030-06-calculate-mean-by-summing-values-and-dividing-by-count" }
l051_09_calculate_mean_absolute_error_as_absolute_error_sum_divided_by_count = { package = "l051-09-calculate-mean-absolute-error-as-absolute-error-sum-divided-by-count", path = "../l051-09-calculate-mean-absolute-error-as-absolute-error-sum-divided-by-count" }
lesson-trace = { path = "../lesson-trace" }

lesson-visualization = { path = "../lesson-visualization" }
