[package]
name = "l241-46-project-compare-train-and-run-prediction-model"
version = "0.1.0"
edition = "2024"

[dependencies]
l030_06_calc_mean_by_summing_values_and_dividing_by_count = { package = "l030-06-calc-mean-by-summing-values-and-dividing-by-count", path = "../l030-06-calc-mean-by-summing-values-and-dividing-by-count" }
l051_09_calc_mean_absolute_error_by_summing_absolute_errors_and_dividing_by_count = { package = "l051-09-calc-mean-absolute-error-by-summing-absolute-errors-and-dividing-by-count", path = "../l051-09-calc-mean-absolute-error-by-summing-absolute-errors-and-dividing-by-count" }

lesson-visualization = { path = "../lesson-visualization" }
