[package]
name = "part-006-lesson-01-practice-coordinate-products-vector-lengths-and-point-distances"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
part_001_lesson_01_calculate_scalar_product_by_multiplying_matching_coordinates_and_adding = { package = "part-001-lesson-01-calculate-scalar-product-by-multiplying-matching-coordinates-and-adding", path = "../part-001-lesson-01-calculate-scalar-product-by-multiplying-matching-coordinates-and-adding" }
part_002_lesson_01_calculate_l1_vector_norm_by_summing_absolute_coordinates = { package = "part-002-lesson-01-calculate-l1-vector-norm-by-summing-absolute-coordinates", path = "../part-002-lesson-01-calculate-l1-vector-norm-by-summing-absolute-coordinates" }
part_003_lesson_01_calculate_vector_length_as_square_root_of_sum_of_squared_coordinates = { package = "part-003-lesson-01-calculate-vector-length-as-square-root-of-sum-of-squared-coordinates", path = "../part-003-lesson-01-calculate-vector-length-as-square-root-of-sum-of-squared-coordinates" }
part_004_lesson_01_calculate_point_distance_as_square_root_of_squared_coordinate_difference_sum = { package = "part-004-lesson-01-calculate-point-distance-as-square-root-of-squared-coordinate-difference-sum", path = "../part-004-lesson-01-calculate-point-distance-as-square-root-of-squared-coordinate-difference-sum" }
part_005_lesson_01_calculate_direction_similarity_as_coordinate_product_sum_divided_by_vector_lengths = { package = "part-005-lesson-01-calculate-direction-similarity-as-coordinate-product-sum-divided-by-vector-lengths", path = "../part-005-lesson-01-calculate-direction-similarity-as-coordinate-product-sum-divided-by-vector-lengths" }

lesson-visualization = { path = "../lesson-visualization" }
