[package]
name = "part-185-lesson-35-end-to-end"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson_029 = { package = "part-029-lesson-06-mean", path = "../part-029-lesson-06-mean" }
lesson_048 = { package = "part-048-lesson-09-mae", path = "../part-048-lesson-09-mae" }

lesson-visualization = { path = "../lesson-visualization" }
