[package]
name = "l070-11-practice-checking-predictions-when-one-class-is-rare"
version = "0.1.0"
edition = "2024"

[dependencies]
l061_11_count_binary_classification_outcomes_from_targets_and_predictions = { package = "l061-11-count-binary-classification-outcomes-from-targets-and-predictions", path = "../l061-11-count-binary-classification-outcomes-from-targets-and-predictions" }
l062_11_count_binary_classification_outcomes_from_targets_and_scores_at_threshold = { package = "l062-11-count-binary-classification-outcomes-from-targets-and-scores-at-threshold", path = "../l062-11-count-binary-classification-outcomes-from-targets-and-scores-at-threshold" }
l063_11_calc_prediction_accuracy_as_correct_predictions_divided_by_all_predictions_where_1_means_all_correct_and_0_means_all_wrong = { package = "l063-11-calc-prediction-accuracy-as-correct-predictions-divided-by-all-predictions-where-1-means-all-correct-and-0-means-all-wrong", path = "../l063-11-calc-prediction-accuracy-as-correct-predictions-divided-by-all-predictions-where-1-means-all-correct-and-0-means-all-wrong" }
l064_11_calc_pos_prediction_precision_as_true_poss_divided_by_pos_predictions_where_1_means_no_false_alarms_and_0_means_all_false_alarms = { package = "l064-11-calc-pos-prediction-precision-as-true-poss-divided-by-pos-predictions-where-1-means-no-false-alarms-and-0-means-all-false-alarms", path = "../l064-11-calc-pos-prediction-precision-as-true-poss-divided-by-pos-predictions-where-1-means-no-false-alarms-and-0-means-all-false-alarms" }
l065_11_calc_pos_detection_recall_as_true_poss_divided_by_actual_poss_where_1_means_all_found_and_0_means_all_missed = { package = "l065-11-calc-pos-detection-recall-as-true-poss-divided-by-actual-poss-where-1-means-all-found-and-0-means-all-missed", path = "../l065-11-calc-pos-detection-recall-as-true-poss-divided-by-actual-poss-where-1-means-all-found-and-0-means-all-missed" }
l066_11_calc_f1_score_as_twice_precision_times_recall_divided_by_their_sum_where_1_means_no_false_alarms_or_misses_and_larger_means_better = { package = "l066-11-calc-f1-score-as-twice-precision-times-recall-divided-by-their-sum-where-1-means-no-false-alarms-or-misses-and-larger-means-better", path = "../l066-11-calc-f1-score-as-twice-precision-times-recall-divided-by-their-sum-where-1-means-no-false-alarms-or-misses-and-larger-means-better" }

lesson-visualization = { path = "../lesson-visualization" }
