[package]
name = "l070-11-practice-checking-predictions-when-one-class-is-rare"
version = "0.1.0"
edition = "2024"

[dependencies]
l061_11_count_binary_classification_outcomes_from_targets_and_predictions = { package = "l061-11-count-binary-classification-outcomes-from-targets-and-predictions", path = "../l061-11-count-binary-classification-outcomes-from-targets-and-predictions" }
l062_11_count_binary_classification_outcomes_from_targets_and_scores_at_threshold = { package = "l062-11-count-binary-classification-outcomes-from-targets-and-scores-at-threshold", path = "../l062-11-count-binary-classification-outcomes-from-targets-and-scores-at-threshold" }
l063_11_calc_prediction_accuracy_as_correct_predictions_divided_by_all_predictions = { package = "l063-11-calc-prediction-accuracy-as-correct-predictions-divided-by-all-predictions", path = "../l063-11-calc-prediction-accuracy-as-correct-predictions-divided-by-all-predictions" }
l064_11_calc_pos_prediction_precision_as_true_poss_divided_by_pos_predictions = { package = "l064-11-calc-pos-prediction-precision-as-true-poss-divided-by-pos-predictions", path = "../l064-11-calc-pos-prediction-precision-as-true-poss-divided-by-pos-predictions" }
l065_11_calc_pos_detection_recall_as_true_poss_divided_by_actual_poss = { package = "l065-11-calc-pos-detection-recall-as-true-poss-divided-by-actual-poss", path = "../l065-11-calc-pos-detection-recall-as-true-poss-divided-by-actual-poss" }
l066_11_calc_f1_score_as_twice_precision_times_recall_divided_by_their_sum = { package = "l066-11-calc-f1-score-as-twice-precision-times-recall-divided-by-their-sum", path = "../l066-11-calc-f1-score-as-twice-precision-times-recall-divided-by-their-sum" }
