[package]
name = "l007-01-practice-multiplying-coordinates-vector-lengths-and-point-distances"
version = "0.1.0"
edition = "2024"

[dependencies]
l001_01_multiply_matching_coordinates_then_add_results = { package = "l001-01-multiply-matching-coordinates-then-add-results", path = "../l001-01-multiply-matching-coordinates-then-add-results" }
l002_01_calculate_sum_of_absolute_vector_coordinates = { package = "l002-01-calculate-sum-of-absolute-vector-coordinates", path = "../l002-01-calculate-sum-of-absolute-vector-coordinates" }
l003_01_calculate_vector_length_as_square_root_of_sum_of_squared_coordinates = { package = "l003-01-calculate-vector-length-as-square-root-of-sum-of-squared-coordinates", path = "../l003-01-calculate-vector-length-as-square-root-of-sum-of-squared-coordinates" }
l005_01_calculate_point_distance_as_square_root_of_squared_coordinate_difference_sum = { package = "l005-01-calculate-point-distance-as-square-root-of-squared-coordinate-difference-sum", path = "../l005-01-calculate-point-distance-as-square-root-of-squared-coordinate-difference-sum" }
l006_01_calculate_cos_of_angle_between_vectors = { package = "l006-01-calculate-cos-of-angle-between-vectors", path = "../l006-01-calculate-cos-of-angle-between-vectors" }

lesson-visualization = { path = "../lesson-visualization" }
