[package]
name = "part-208-lesson-40-compare-fixed-and-input-controlled-memory-retention"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
part-206-lesson-40-repeatedly-add-weighted-input-to-retained-previous-state = { path = "../part-206-lesson-40-repeatedly-add-weighted-input-to-retained-previous-state" }
lesson-visualization = { path = "../lesson-visualization" }
