//! Урок 067. F1 из счётчиков: вычисление точности и полноты и их гармонического среднего.

/// Получаем обе метрики из счётчиков предыдущих уроков.
/// F1 из счётчиков: находим precision и recall, затем делим их удвоенное произведение на сумму.
use l061_11_count_correct_and_incorrect_positive_and_negative_predictions::BinaryClassificationCounts;
use l064_11_calculate_positive_prediction_precision_as_true_positives_over_positive_predictions::calculate_positive_prediction_precision_as_true_positives_divided_by_positive_predictions_where_1_means_no_false_alarms_and_0_means_all_false_alarms;
use l065_11_calculate_positive_detection_recall_as_found_positives_over_actual_positives::calculate_positive_detection_recall_as_true_positives_divided_by_actual_positives_where_1_means_all_found_and_0_means_all_missed;
use l066_11_calculate_f1_score_as_twice_precision_times_recall_over_their_sum::calculate_f1_score_as_twice_precision_times_recall_divided_by_their_sum_where_1_means_no_false_alarms_or_misses_and_larger_means_better;

pub fn calculate_f1_score_from_counts_by_multiplying_precision_and_recall_by_two_then_dividing_by_sum_where_1_means_no_false_alarms_or_misses_and_larger_means_better(
    counts: BinaryClassificationCounts,
) -> Option<f64> {
    calculate_f1_score_as_twice_precision_times_recall_divided_by_their_sum_where_1_means_no_false_alarms_or_misses_and_larger_means_better(
        calculate_positive_prediction_precision_as_true_positives_divided_by_positive_predictions_where_1_means_no_false_alarms_and_0_means_all_false_alarms(
            counts,
        ),
        calculate_positive_detection_recall_as_true_positives_divided_by_actual_positives_where_1_means_all_found_and_0_means_all_missed(counts),
    )
}
