[package]
name = "part-160-lesson-30-cosine-similarity-between-query-and-document-vectors"
version = "0.1.0"
edition = "2024"

[dependencies]
part_005_lesson_01_cosine_similarity_between_two_vectors = { package = "part-005-lesson-01-cosine-similarity-between-two-vectors", path = "../part-005-lesson-01-cosine-similarity-between-two-vectors" }
lesson-visualization = { path = "../lesson-visualization" }
