[package]
name = "part-005-lesson-01-cosine-similarity-between-two-vectors"
version = "0.1.0"
edition = "2024"

[dependencies]
part_001_lesson_01_multiply_matching_coordinates_of_two_vectors_then_add = { package = "part-001-lesson-01-multiply-matching-coordinates-of-two-vectors-then-add", path = "../part-001-lesson-01-multiply-matching-coordinates-of-two-vectors-then-add" }
part_003_lesson_01_calculate_euclidean_length_of_one_vector = { package = "part-003-lesson-01-calculate-euclidean-length-of-one-vector", path = "../part-003-lesson-01-calculate-euclidean-length-of-one-vector" }

lesson-visualization = { path = "../lesson-visualization" }
