[package]
name = "part-004-lesson-01-square-root-of-sum-of-squared-coordinate-differences"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
part_003_lesson_01_square_root_of_sum_of_squared_vector_coordinates = { package = "part-003-lesson-01-square-root-of-sum-of-squared-vector-coordinates", path = "../part-003-lesson-01-square-root-of-sum-of-squared-vector-coordinates" }

lesson-visualization = { path = "../lesson-visualization" }
