[package]
name = "part-066-lesson-11-binary-classification-metrics-under-class-imbalance"
version = "0.1.0"
edition = "2024"

[dependencies]
part_060_lesson_11_binary_classification_confusion_matrix_from_true_and_predicted_labels = { package = "part-060-lesson-11-binary-classification-confusion-matrix-from-true-and-predicted-labels", path = "../part-060-lesson-11-binary-classification-confusion-matrix-from-true-and-predicted-labels" }
part_061_lesson_11_precision_from_binary_classification_counts = { package = "part-061-lesson-11-precision-from-binary-classification-counts", path = "../part-061-lesson-11-precision-from-binary-classification-counts" }
part_062_lesson_11_recall_from_binary_classification_counts = { package = "part-062-lesson-11-recall-from-binary-classification-counts", path = "../part-062-lesson-11-recall-from-binary-classification-counts" }
part_063_lesson_11_harmonic_mean_of_binary_classification_precision_and_recall = { package = "part-063-lesson-11-harmonic-mean-of-binary-classification-precision-and-recall", path = "../part-063-lesson-11-harmonic-mean-of-binary-classification-precision-and-recall" }

lesson-visualization = { path = "../lesson-visualization" }
