[package]
name = "l211-39-recover-clean-signal-by-subtracting-scaled-noise-and-dividing-by-signal-scale"
version = "0.1.0"
edition = "2024"

[dependencies]
l209_39_calculate_noisy_signal_by_mixing_signal_and_noise_with_root_variance_share_weights = { package = "l209-39-calculate-noisy-signal-by-mixing-signal-and-noise-with-root-variance-share-weights", path = "../209-39-calculate-noisy-signal-by-mixing-signal-and-noise-with-root-variance-share-weights" }
lesson-trace = { path = "../lesson-trace" }
