[package]
name = "part-005-lesson-01-cosine-similarity"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson_001 = { package = "part-001-lesson-01-multiply-coordinates-and-add", path = "../part-001-lesson-01-multiply-coordinates-and-add" }
lesson_003 = { package = "part-003-lesson-01-l2-norm", path = "../part-003-lesson-01-l2-norm" }
