[package]
name = "part-135-lesson-25-calculate-memory-parameter-influence-by-passing-error-changes-back-in-time"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
part-134-lesson-25-update-memory-from-weighted-input-and-previous-memory = { path = "../part-134-lesson-25-update-memory-from-weighted-input-and-previous-memory" }
