[package]
name = "part-062-lesson-11-divide-detected-positives-by-all-actual-positives"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
part_060_lesson_11_count_correct_and_incorrect_positive_and_negative_predictions = { package = "part-060-lesson-11-count-correct-and-incorrect-positive-and-negative-predictions", path = "../part-060-lesson-11-count-correct-and-incorrect-positive-and-negative-predictions" }

lesson-visualization = { path = "../lesson-visualization" }
