[package]
name = "part-185-lesson-35-calculate-next-token-loss-as-negative-log-correct-token-probability"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
part-182-lesson-35-calculate-past-context-by-summing-current-and-past-values-with-match-weights = { path = "../part-182-lesson-35-calculate-past-context-by-summing-current-and-past-values-with-match-weights" }
lesson-visualization = { path = "../lesson-visualization" }
