[package]
name = "part-139-lesson-26-expand-filter-history-by-increasing-gaps-between-used-past-values"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
part-138-lesson-26-calculate-causal-filter-output-by-summing-weighted-current-and-past-values = { path = "../part-138-lesson-26-calculate-causal-filter-output-by-summing-weighted-current-and-past-values" }
lesson-visualization = { path = "../lesson-visualization" }
