[package]
name = "l063-11-calc-prediction-accuracy-as-correct-predictions-divided-by-all-predictions"
version = "0.1.0"
edition = "2024"

[dependencies]
l061_11_count_binary_classification_outcomes_from_targets_and_predictions = { package = "l061-11-count-binary-classification-outcomes-from-targets-and-predictions", path = "../l061-11-count-binary-classification-outcomes-from-targets-and-predictions" }

[dev-dependencies]
lesson-float-comparison = { path = "../lesson-float-comparison" }
