[package]
name = "l063-11-calc-prediction-accuracy-as-correct-predictions-divided-by-all-predictions"
version = "0.1.0"
edition = "2024"

[dependencies]
l061_11_count_binary_classification_outcomes_from_targets_and_predictions.workspace = true

[dev-dependencies]
lesson-float-comparison.workspace = true
