[package]
name = "l164-30-calculate-query-document-direction-similarity-as-product-sum-over-vector-lengths"
version = "0.1.0"
edition = "2024"

[dependencies]
l006_01_calculate_direction_similarity_as_coordinate_product_sum_divided_by_vector_lengths = { package = "l006-01-calculate-direction-similarity-as-coordinate-product-sum-divided-by-vector-lengths", path = "../l006-01-calculate-direction-similarity-as-coordinate-product-sum-divided-by-vector-lengths" }
lesson-visualization = { path = "../lesson-visualization" }
