[package]
name = "part-031-lesson-06-sample-variance-of-numeric-values"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
part_029_lesson_06_arithmetic_mean_of_numeric_values = { package = "part-029-lesson-06-arithmetic-mean-of-numeric-values", path = "../part-029-lesson-06-arithmetic-mean-of-numeric-values" }

lesson-visualization = { path = "../lesson-visualization" }
