"""Generate the checked-in concept diagrams used in LEARNING_PLAN.md.

Run: python3 scripts/generate_illustrations.py
The figures are intentionally independent of the SVG charts generated by lessons.
"""

from html import escape
from pathlib import Path

OUTPUT = Path(__file__).resolve().parents[1] / "docs" / "illustrations"
OUTPUT.mkdir(parents=True, exist_ok=True)
NAVY = "#14213d"
MUTED = "#52627a"
BLUE = "#2459c6"
BLUE_LIGHT = "#e8efff"
ORANGE = "#d97725"
ORANGE_LIGHT = "#fff0df"
GREEN = "#17845a"
GREEN_LIGHT = "#e4f6ee"
RED = "#c84352"
RED_LIGHT = "#fde9ec"
BORDER = "#d8e1ef"


def text(x, y, value, size=18, color=NAVY, weight=400, anchor="start"):
    return (f'<text x="{x}" y="{y}" fill="{color}" font-size="{size}" '
            f'font-weight="{weight}" text-anchor="{anchor}">{escape(value)}</text>')


def rect(x, y, width, height, fill="white", stroke=BORDER, radius=16, stroke_width=1.5):
    return (f'<rect x="{x}" y="{y}" width="{width}" height="{height}" rx="{radius}" '
            f'fill="{fill}" stroke="{stroke}" stroke-width="{stroke_width}"/>')


def line(x1, y1, x2, y2, color=MUTED, width=2, marker=""):
    end = f' marker-end="url(#{marker})"' if marker else ""
    return (f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" '
            f'stroke="{color}" stroke-width="{width}" stroke-linecap="round"{end}/>')


def circle(x, y, radius, fill, stroke="none"):
    return f'<circle cx="{x}" cy="{y}" r="{radius}" fill="{fill}" stroke="{stroke}"/>'


def pill(x, y, width, label, fill, color):
    return rect(x, y, width, 34, fill, fill, 17, 0) + text(x + width / 2, y + 23, label, 15, color, 700, "middle")


def write(name, height, title, description, body):
    definitions = f'''<defs>
      <marker id="blue-arrow" markerWidth="10" markerHeight="10" refX="8" refY="5" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z" fill="{BLUE}"/></marker>
      <marker id="orange-arrow" markerWidth="10" markerHeight="10" refX="8" refY="5" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z" fill="{ORANGE}"/></marker>
      <marker id="gray-arrow" markerWidth="10" markerHeight="10" refX="8" refY="5" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z" fill="{MUTED}"/></marker>
    </defs>'''
    heading = text(48, 56, title, 30, NAVY, 700) + text(48, 89, description, 17, MUTED)
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="{height}" '
           f'viewBox="0 0 1200 {height}" role="img" aria-labelledby="title description">'
           f'<title id="title">{escape(title)}</title><desc id="description">{escape(description)}</desc>'
           f'<rect width="1200" height="{height}" fill="#f8fbff"/>{definitions}'
           f'<g font-family="DejaVu Sans, Arial, sans-serif">{heading}{body}</g></svg>')
    (OUTPUT / name).write_text(svg + "\n", encoding="utf-8")


# 01. Three angles for the fixed left vector [1, 2].
body = ""
vector_cases = [
    ("Острый угол", "[2, 1]", "1·2 + 2·1 = 4", GREEN, GREEN_LIGHT, 110, -55),
    ("Прямой угол", "[-2, 1]", "1·(-2) + 2·1 = 0", ORANGE, ORANGE_LIGHT, -110, -55),
    ("Тупой угол", "[-3, 1]", "1·(-3) + 2·1 = -1", RED, RED_LIGHT, -135, -45),
]
for index, (heading, right_label, formula, result_color, pale, second_x, second_y) in enumerate(vector_cases):
    left = 42 + index * 388
    body += rect(left, 118, 360, 326)
    body += pill(left + 18, 136, 150, heading, pale, result_color)
    origin_x, origin_y = left + 176, 326
    body += line(left + 32, origin_y, left + 328, origin_y, "#bac7d9", 1.5)
    body += line(origin_x, 362, origin_x, 204, "#bac7d9", 1.5)
    body += circle(origin_x, origin_y, 4, NAVY)
    body += line(origin_x, origin_y, origin_x + 55, origin_y - 110, BLUE, 5, "blue-arrow")
    body += line(origin_x, origin_y, origin_x + second_x, origin_y + second_y, ORANGE, 5, "orange-arrow")
    body += text(origin_x + 62, origin_y - 116, "a = [1, 2]", 15, BLUE, 700)
    label_x = origin_x + second_x + (8 if second_x >= 0 else -8)
    body += text(label_x, origin_y + second_y - 9, "b = " + right_label, 15, ORANGE, 700,
                 "start" if second_x >= 0 else "end")
    body += text(left + 180, 405, formula, 18, result_color, 700, "middle")
body += text(600, 481, "Знак результата зависит от угла; нулевой вектор не имеет направления.", 17, MUTED, 400, "middle")
write("01-dot-product.svg", 510, "Скалярное произведение и угол", "Один вектор a, три направления второго вектора b", body)


# 05. A fraction is a part of one whole and can also be a probability threshold.
body = ""
for index, (value, pieces, caption) in enumerate([
    ("0.25", 1, "1 из 4 частей"),
    ("0.50", 2, "2 из 4 частей"),
    ("0.75", 3, "3 из 4 частей"),
]):
    x = 44 + index * 384
    body += rect(x, 132, 344, 250)
    body += text(x + 24, 177, f"fraction = {value}", 23, BLUE, 700)
    for piece in range(4):
        body += rect(x + 24 + piece * 75, 205, 68, 64,
                     BLUE if piece < pieces else "white", BLUE, 5, 1.5)
    body += text(x + 24, 308, caption, 18, NAVY, 700)
    body += text(x + 24, 345, f"{pieces}/4 = {value}", 17, MUTED)
body += rect(91, 411, 1018, 72, GREEN_LIGHT, GREEN)
body += text(600, 440, "Пример: случайное число 0.37 < fraction 0.50", 20, NAVY, 700, "middle")
body += text(600, 468, "значит, событие с вероятностью 0.50 произошло", 17, GREEN, 600, "middle")
write("05-fraction.svg", 520, "Fraction — доля целого", "0 означает ничего, 1 означает целое; между ними — часть целого", body)


# 07. A data split is a workflow with one-way information flow.
body = rect(426, 113, 348, 74, BLUE_LIGHT, BLUE)
body += text(600, 146, "Исходные данные", 23, BLUE, 700, "middle")
body += text(600, 172, "разделить до настройки модели", 15, MUTED, 400, "middle")
columns = [
    (44, "train", "Подогнать преобразования", "Обучить параметры модели", BLUE, BLUE_LIGHT),
    (430, "validation", "Выбрать настройки и порог", "Не переобучать преобразования", ORANGE, ORANGE_LIGHT),
    (816, "test", "Оценить один раз в конце", "Не выбирать по нему настройки", GREEN, GREEN_LIGHT),
]
for x, heading, step_one, step_two, color, pale in columns:
    center = x + 170
    body += line(600, 187, center, 236, MUTED, 2.5, "gray-arrow")
    body += rect(x, 248, 340, 218, "white", color, 18, 2)
    body += pill(x + 20, 267, 126, heading, pale, color)
    body += text(x + 20, 340, step_one, 17, NAVY, 700)
    body += text(x + 20, 379, step_two, 15, MUTED)
    body += line(x + 20, 403, x + 320, 403, BORDER, 1)
    body += text(x + 20, 440, "Роль данных неизменна", 15, color, 700)
body += text(600, 512, "Среднее, словарь и другие обучаемые преобразования вычисляются только на train.", 17, NAVY, 600, "middle")
write("07-data-split.svg", 545, "Разделение данных без утечки", "Три части данных отвечают на разные вопросы", body)


# 11. Truth is in rows, predictions in columns.
body = text(485, 130, "Прогноз модели", 20, NAVY, 700, "middle")
body += text(442, 166, "положительный", 16, BLUE, 700, "middle")
body += text(742, 166, "отрицательный", 16, BLUE, 700, "middle")
body += text(140, 320, "Истинный класс", 20, NAVY, 700, "middle")
body += text(250, 267, "положительный", 15, MUTED, 700, "middle")
body += text(250, 414, "отрицательный", 15, MUTED, 700, "middle")
confusion_cells = [
    (302, 183, GREEN_LIGHT, GREEN, "TP", "нашли положительный", "истина +, прогноз +"),
    (602, 183, ORANGE_LIGHT, ORANGE, "FN", "пропустили положительный", "истина +, прогноз −"),
    (302, 330, RED_LIGHT, RED, "FP", "ложная тревога", "истина −, прогноз +"),
    (602, 330, BLUE_LIGHT, BLUE, "TN", "нашли отрицательный", "истина −, прогноз −"),
]
for x, y, pale, color, code, meaning, pair in confusion_cells:
    body += rect(x, y, 280, 130, pale, color, 14, 1.5)
    body += text(x + 20, y + 42, code, 27, color, 700)
    body += text(x + 20, y + 76, meaning, 15, NAVY, 700)
    body += text(x + 20, y + 103, pair, 14, MUTED)
body += rect(920, 183, 234, 277, "white", BORDER)
body += text(940, 219, "Пример урока", 19, NAVY, 700)
body += text(940, 260, "Истина:   +  −  +  −", 16, MUTED)
body += text(940, 293, "Прогноз: +  +  −  −", 16, MUTED)
body += line(940, 316, 1134, 316, BORDER, 1)
body += text(940, 354, "По одному объекту", 15, NAVY)
body += text(940, 382, "в каждой ячейке.", 15, NAVY)
body += text(940, 433, "TP+FN = все +", 14, BLUE, 700)
body += text(600, 508, "Каждый объект попадает ровно в одну ячейку.", 17, MUTED, 400, "middle")
write("11-confusion-matrix.svg", 540, "Матрица ошибок классификации", "Строки показывают истину, столбцы — прогноз модели", body)


# 26. A filter at time 3 can read time 3 and time 2 only.
body = text(48, 136, "Входной сигнал", 21, NAVY, 700)
values = [1, 0, 2, 3, 9]
for index, value in enumerate(values):
    x = 170 + index * 190
    fill = BLUE_LIGHT if index in (2, 3) else (RED_LIGHT if index == 4 else "white")
    stroke = BLUE if index in (2, 3) else (RED if index == 4 else BORDER)
    body += rect(x, 162, 156, 100, fill, stroke, 14, 2)
    body += text(x + 78, 203, f"x{index} = {value}", 23, stroke, 700, "middle")
    body += text(x + 78, 238, f"момент {index}", 14, MUTED, 400, "middle")
body += text(550, 304, "прошлый вход × 2", 15, BLUE, 700, "middle")
body += text(785, 304, "текущий вход × 1", 15, BLUE, 700, "middle")
body += text(1008, 304, "будущее закрыто", 15, RED, 700, "middle")
body += line(170 + 2 * 190 + 78, 267, 600, 352, BLUE, 3, "blue-arrow")
body += line(170 + 3 * 190 + 78, 267, 670, 352, BLUE, 3, "blue-arrow")
body += line(170 + 4 * 190 + 50, 172, 170 + 4 * 190 + 106, 252, RED, 4)
body += line(170 + 4 * 190 + 106, 172, 170 + 4 * 190 + 50, 252, RED, 4)
body += rect(424, 368, 352, 105, GREEN_LIGHT, GREEN, 18, 2)
body += text(600, 408, "y3 = 2·x2 + 1·x3", 23, NAVY, 700, "middle")
body += text(600, 446, "2·2 + 1·3 = 7", 22, GREEN, 700, "middle")
body += text(600, 521, "Изменение x4 не может изменить y3.", 18, MUTED, 600, "middle")
write("26-causal-convolution.svg", 550, "Причинная свёртка", "Выход в момент 3 использует текущий и прошлый входы", body)


# 31. Attention: operations and a causal weight matrix.
body = ""
steps = [
    (34, "Q × Kᵀ", "оценки"),
    (262, "Маска", "будущее закрыто"),
    (490, "softmax", "сумма строки = 1"),
    (718, "Вес × V", "смесь значений"),
]
for x, heading, sub in steps:
    body += rect(x, 129, 198, 95, "white", BORDER)
    body += text(x + 99, 169, heading, 20, NAVY, 700, "middle")
    body += text(x + 99, 200, sub, 14, MUTED, 400, "middle")
    if x != 718:body += line(x + 202, 177, x + 224, 177, MUTED, 2, "gray-arrow")
body += rect(944, 129, 222, 95, GREEN_LIGHT, GREEN)
body += text(1055, 169, "Новый вектор", 19, GREEN, 700, "middle")
body += text(1055, 200, "для каждой позиции", 14, MUTED, 400, "middle")
body += line(922, 177, 940, 177, MUTED, 2, "gray-arrow")
body += text(80, 290, "Веса внимания после маски и softmax", 20, NAVY, 700)
body += text(100, 347, "запрос ↓ / ключ →", 15, MUTED)
weights = [["1.00", "0", "0"], ["0.30", "0.70", "0"], ["0.20", "0.30", "0.50"]]
for row_index, row in enumerate(weights):
    body += text(336, 394 + row_index * 66, f"позиция {row_index + 1}", 15, MUTED, 600, "end")
    for column_index, value in enumerate(row):
        x, y = 365 + column_index * 152, 350 + row_index * 66
        future = column_index > row_index
        fill = RED_LIGHT if future else BLUE_LIGHT
        stroke = RED if future else BLUE
        body += rect(x, y, 135, 54, fill, stroke, 9, 1)
        body += text(x + 67, y + 35, value, 20, stroke, 700, "middle")
for column_index in range(3):
    body += text(432 + column_index * 152, 336, f"позиция {column_index + 1}", 15, MUTED, 600, "middle")
body += rect(860, 336, 292, 190, "white", BORDER)
body += text(881, 371, "Красные ячейки", 18, RED, 700)
body += text(881, 401, "всегда имеют вес 0:", 16, NAVY)
body += text(881, 431, "прошлое не видит будущее.", 16, NAVY)
body += line(881, 451, 1132, 451, BORDER, 1)
body += text(881, 487, "Сумма каждой строки = 1", 15, BLUE, 700)
body += text(600, 581, "Вес определяет вклад значения V в выход соответствующей позиции.", 18, MUTED, 400, "middle")
write("31-attention.svg", 610, "Как работает причинное внимание", "Запросы и ключи задают веса, значения V дают содержимое выхода", body)


# 39. Numeric storyboard using the actual forward diffusion formula from lesson 39.1.
body = rect(44, 120, 1112, 68, BLUE_LIGHT, BLUE)
body += text(600, 164, "x = √ᾱ · 2  +  √(1−ᾱ) · (−1)", 23, BLUE, 700, "middle")
stages = [
    ("1.00", "2.00", "2.00 + 0.00", 1.0),
    ("0.75", "1.23", "1.73 − 0.50", 0.75),
    ("0.25", "0.13", "1.00 − 0.87", 0.25),
    ("0.00", "−1.00", "0.00 − 1.00", 0.0),
]
for index, (share, result, terms, clean_share) in enumerate(stages):
    x = 44 + index * 286
    body += rect(x, 219, 254, 250, "white", BORDER)
    body += pill(x + 19, 237, 122, "ᾱ = " + share, BLUE_LIGHT, BLUE)
    body += text(x + 19, 317, "выход " + result, 25, NAVY, 700)
    body += text(x + 19, 353, terms, 17, MUTED)
    body += rect(x + 19, 388, 216, 20, ORANGE_LIGHT, ORANGE_LIGHT, 10, 0)
    if clean_share > 0:
        body += rect(x + 19, 388, 216 * clean_share, 20, BLUE, BLUE, 10, 0)
    body += text(x + 19, 437, "синий: доля ᾱ", 13, BLUE, 600)
    if index < 3:body += line(x + 257, 337, x + 282, 337, MUTED, 2, "gray-arrow")
body += text(600, 515, "При ᾱ = 1 остаётся чистый сигнал; при ᾱ = 0 остаётся только шум.", 17, MUTED, 600, "middle")
write("39-diffusion.svg", 545, "От сигнала к шуму", "Чистый сигнал 2, фиксированный шум −1, меняется только ᾱ", body)

print("Generated", len(list(OUTPUT.glob("*.svg"))), "illustrations in", OUTPUT)
