[package]
name = "l062-11-count-binary-classification-outcomes-from-targets-and-scores-at-threshold"
version = "0.1.0"
edition = "2024"

[dependencies]
l061_11_count_binary_classification_outcomes_from_targets_and_predictions.workspace = true

[dev-dependencies]
lesson-float-comparison.workspace = true
