[package]
name = "l147-27-compare-byte-splitting-and-learned-text-pieces-on-new-strings"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
l144-27-learn-text-units-by-merging-most-frequent-adjacent-byte-pairs = { path = "../144-27-learn-text-units-by-merging-most-frequent-adjacent-byte-pairs" }
lesson-visualization = { path = "../lesson-visualization" }
