[package]
name = "part-054-lesson-09-practice-fitting-a-line-and-checking-prediction-errors"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-trace = { path = "../lesson-trace" }
part_049_lesson_09_sum_squared_prediction_errors_and_divide_by_count = { package = "part-049-lesson-09-sum-squared-prediction-errors-and-divide-by-count", path = "../part-049-lesson-09-sum-squared-prediction-errors-and-divide-by-count" }

lesson-visualization = { path = "../lesson-visualization" }
