[package]
name = "l003-01-calculate-vector-length-as-square-root-of-sum-of-squared-coordinates"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-float-comparison = { path = "../lesson-float-comparison" }
l001_01_multiply_matching_coordinates_then_add_results = { package = "l001-01-multiply-matching-coordinates-then-add-results", path = "../l001-01-multiply-matching-coordinates-then-add-results" }

lesson-visualization = { path = "../lesson-visualization" }
