[package]
name = "part-191-lesson-36-query-key-normalization"
version = "0.1.0"
edition = "2024"

[dependencies]
part-188-lesson-36-root-mean-square-normalization = { path = "../part-188-lesson-36-root-mean-square-normalization" }
part-189-lesson-36-rotary-position-embedding = { path = "../part-189-lesson-36-rotary-position-embedding" }
