[package]
name = "lesson-datasets"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
part-004-lesson-01-square-root-of-sum-of-squared-coordinate-differences = { path = "../part-004-lesson-01-square-root-of-sum-of-squared-coordinate-differences" }
part-029-lesson-06-sum-values-and-divide-by-count = { path = "../part-029-lesson-06-sum-values-and-divide-by-count" }
part-049-lesson-09-sum-squared-prediction-errors-and-divide-by-count = { path = "../part-049-lesson-09-sum-squared-prediction-errors-and-divide-by-count" }
part-050-lesson-09-sum-absolute-prediction-errors-and-divide-by-count = { path = "../part-050-lesson-09-sum-absolute-prediction-errors-and-divide-by-count" }
part-060-lesson-11-count-correct-and-incorrect-positive-and-negative-predictions = { path = "../part-060-lesson-11-count-correct-and-incorrect-positive-and-negative-predictions" }
part-062-lesson-11-divide-detected-positives-by-all-actual-positives = { path = "../part-062-lesson-11-divide-detected-positives-by-all-actual-positives" }
