[package]
name = "part-208-lesson-40-compare-input-dependent-and-fixed-state-forgetting"
version = "0.1.0"
edition = "2024"

[dependencies]
part-206-lesson-40-calculate-linear-recurrent-state-over-input-sequence = { path = "../part-206-lesson-40-calculate-linear-recurrent-state-over-input-sequence" }
lesson-visualization = { path = "../lesson-visualization" }
