[package]
name = "part-164-lesson-31-key-vector-for-attention-position"
version = "0.1.0"
edition = "2024"

[dependencies]
part_001_lesson_01_multiply_matching_coordinates_of_two_vectors_then_add = { package = "part-001-lesson-01-multiply-matching-coordinates-of-two-vectors-then-add", path = "../part-001-lesson-01-multiply-matching-coordinates-of-two-vectors-then-add" }

lesson-visualization = { path = "../lesson-visualization" }
