[package]
name = "l211-39-recover-clean-signal-by-subtracting-scaled-noise-then-dividing-by-signal-scale"
version = "0.1.0"
edition = "2024"

[dependencies]
lesson-float-comparison.workspace = true
l209_39_calc_noisy_signal_by_mixing_signal_and_noise_using_square_roots_of_variance_shares.workspace = true
