[package]
name = "l107-19-find-principal-direction-by-maximizing-projected-point-spread"
version = "0.1.0"
edition = "2024"

[dependencies]
l001_01_multiply_matching_coords_then_add_results = { package = "l001-01-multiply-matching-coords-then-add-results", path = "../l001-01-multiply-matching-coords-then-add-results" }

lesson-visualization = { path = "../lesson-visualization" }
